
app = "marta"
primary_region = "mad"

[build]

[deploy]

[http_service]
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
